// vue-rx/src/app/User.vue
<template>
  <div class="login">
    <!-- https://jsfiddle.net/fddxe9zd/ -->
    <div v-if="userData && userData.token" class="logged-in">
      <p v-show="userData.token"> Logged in! </p>
      <button v-show="userData.token" name="logout"> Logout </button>
    </div>
    <p v-if="loginData && loginData.error"> {{ loginData.error }} </p>
    <p v-if="loginData && loginData.message"> {{ loginData.message }} </p>
    <div v-if="!userData || !userData.token" class="not-logged-in">
      <div>
        Login:
        <input type="text" placeholder="email" name="email" v-model="email"/>
        <input type="text" placeholder="password will be sent as plain text" name="password" v-model="password"/>
        <button name="login"> Login </button>
      </div>

      <div>
        Register:
        <input type="text" placeholder="email" name="reg-email" v-model="regEmail"/>
        <input type="text" placeholder="password will be sent as plain text" name="reg-password" v-model="regPassword"/>
        <button name="register"> Register </button>
      </div>
    </div>
  </div>
</template>

<script>
 import Rx from 'rxjs/Rx'
 import {login, logout, register} from '../util/auth'
 import {state$} from '../util/state.js'
 export default {
   name: 'User',
   data() {
     return {
       email: '',
       password: '',
       regEmail: '',
       regPassword: ''
     }
   },
   subscriptions() {
     const logout$ = this.$fromDOMEvent('button[name=logout]', 'click')
                         .do(_ => console.log('hoh'))
                         .do(_ => logout())
     const email = this.$watchAsObservable('email').pluck('newValue')
     const password = this.$watchAsObservable('password').pluck('newValue')
     const creds = email.combineLatest(password)

     const loginRes = this.$fromDOMEvent('button[name=login]', 'click')
                          .withLatestFrom(creds, (_, [email, pass]) => [email, pass])
                          .switchMap(([email, password]) => login({email, password}))

     const registerEmail = this.$watchAsObservable('regEmail').pluck('newValue')
     const registerPass = this.$watchAsObservable('regPassword').pluck('newValue')
     const regCreds = registerEmail.combineLatest(registerPass)

     const registerRes = this.$fromDOMEvent('button[name=register]', 'click')
           .do(e=>console.log(e))
           .withLatestFrom(regCreds, (_, [email, pass]) => [email, pass])
           .do(e=>console.log(e))
           .switchMap(([email, password]) => register({email, password}))
           .do(e=>console.log(e))

     const logState = loginRes.merge(registerRes);
     return {
       userData: state$,
       //loginData: loginRes,
       loginData: logState,
       logout$
     }
   }
 }
</script>

<style lang="sass">
 .login {
   background-color: white;
 }
</style>

// react/src/components/UserComponent.js
'use strict';

import React from 'react'
import R from 'react.reactive'
import Rx from 'rxjs/Rx'

require('styles//User.css');

import {state$, newStateObservable} from '../util/state.js'
import {login} from '../util/auth.js'

const userData = state$
const loginData = state$

const Messages = (props) => (
  <R.div>
    {userData && userData.token
     ? <div class="logged-in">
          <p v-show="userData.token"> Logged in! </p>
          <button v-show="userData.token" name="logout"> Logout </button>
       </div>
     : null}
  {loginData && loginData.error
   ? <p> {loginData.error} </p>
   : null
  }
  {loginData && loginData.message
   ? <p> {loginData.message} </p>
   : null
  }
  </R.div>
)

const getInputVal = (selector) => {
  return document.querySelector(selector).value
}

const getCreds = () => {
  return {
    email: getInputVal('input[name=log-email]'),
    password: getInputVal('input[name=log-password]')
  }
}

const Login = R(({events}) => {
  const clicked = Rx.Observable.fromEvent(events, 'login-btn')
        .map(() => getCreds())
        .filter(c => c.email && c.password)
        .switchMap((creds) => login(creds))
        .do(_ => console.log('response'))
        .do(e => console.log(e))
  return (
    <div>
      Login:
      <input type="text" placeholder="email" name="log-email"/>
      <input type="text" placeholder="password will be sent as plain text" name="log-password"/>
      <R.button emits={{click: "login-btn"}} name="login"> Login </R.button>
      <R.div>{clicked}</R.div>
    </div>
  )
})

const Register = (props) => (
    <div>
      Register:
      <input type="text" placeholder="email" name="reg-email" />
      <input type="text" placeholder="password will be sent as plain text" name="reg-password"/>
      <button name="register"> Register </button>
    </div>
)

const UserComponent = (props) => (
    <div className="pomodoro-component">
    <Messages/>
    {!userData || !userData.token
     ? <div> <Login/> <Register/> </div>
     : null
    }
  </div>
)

UserComponent.displayName = 'UserComponent';

// Uncomment properties you need
// PomodoroComponent.propTypes = {};
// PomodoroComponent.defaultProps = {};

export default UserComponent;
